services:
  nodeapp:
    container_name: kirana-stop
    build:
      context: .
      dockerfile: Dockerfile
    image: kirana-stop
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always