apiVersion: v1
kind: Namespace
metadata:
  name: "2401061"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kirana-stop-deployment
  namespace: "2401061"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kirana-stop

  template:
    metadata:
      labels:
        app: kirana-stop

    spec:
      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: kirana-stop
          image: 127.0.0.1:30085/2401061/kirana-stop:latest

          ports:
            - containerPort: 3000

          env:
            # Normal config
            - name: PORT
              value: "3000"

            - name: BASE_URL
              value: "http://2401061.imcc.com"

            - name: DEBUG
              value: "0"

            # Secrets (from Jenkins-created K8s Secret)
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: MONGODB_URL

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: JWT_SECRET_KEY

            - name: SESSION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: SESSION_SECRET_KEY

            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: EMAIL_USER

            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: EMAIL_PASS

            - name: SECRET_RESET_KEY
              valueFrom:
                secretKeyRef:
                  name: kirana-stop-secret
                  key: SECRET_RESET_KEY

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"